# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_eigenfaces', [dirname(__file__)])
        except ImportError:
            import _eigenfaces
            return _eigenfaces
        if fp is not None:
            try:
                _mod = imp.load_module('_eigenfaces', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _eigenfaces = swig_import_helper()
    del swig_import_helper
else:
    import _eigenfaces
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _eigenfaces.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _eigenfaces.SwigPyIterator_value(self)
    def incr(self, n=1): return _eigenfaces.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _eigenfaces.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _eigenfaces.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _eigenfaces.SwigPyIterator_equal(self, *args)
    def copy(self): return _eigenfaces.SwigPyIterator_copy(self)
    def next(self): return _eigenfaces.SwigPyIterator_next(self)
    def __next__(self): return _eigenfaces.SwigPyIterator___next__(self)
    def previous(self): return _eigenfaces.SwigPyIterator_previous(self)
    def advance(self, *args): return _eigenfaces.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _eigenfaces.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _eigenfaces.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _eigenfaces.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _eigenfaces.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _eigenfaces.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _eigenfaces.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _eigenfaces.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _eigenfaces.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _eigenfaces.IntVector___nonzero__(self)
    def __bool__(self): return _eigenfaces.IntVector___bool__(self)
    def __len__(self): return _eigenfaces.IntVector___len__(self)
    def pop(self): return _eigenfaces.IntVector_pop(self)
    def __getslice__(self, *args): return _eigenfaces.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _eigenfaces.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _eigenfaces.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _eigenfaces.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _eigenfaces.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _eigenfaces.IntVector___setitem__(self, *args)
    def append(self, *args): return _eigenfaces.IntVector_append(self, *args)
    def empty(self): return _eigenfaces.IntVector_empty(self)
    def size(self): return _eigenfaces.IntVector_size(self)
    def clear(self): return _eigenfaces.IntVector_clear(self)
    def swap(self, *args): return _eigenfaces.IntVector_swap(self, *args)
    def get_allocator(self): return _eigenfaces.IntVector_get_allocator(self)
    def begin(self): return _eigenfaces.IntVector_begin(self)
    def end(self): return _eigenfaces.IntVector_end(self)
    def rbegin(self): return _eigenfaces.IntVector_rbegin(self)
    def rend(self): return _eigenfaces.IntVector_rend(self)
    def pop_back(self): return _eigenfaces.IntVector_pop_back(self)
    def erase(self, *args): return _eigenfaces.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _eigenfaces.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _eigenfaces.IntVector_push_back(self, *args)
    def front(self): return _eigenfaces.IntVector_front(self)
    def back(self): return _eigenfaces.IntVector_back(self)
    def assign(self, *args): return _eigenfaces.IntVector_assign(self, *args)
    def resize(self, *args): return _eigenfaces.IntVector_resize(self, *args)
    def insert(self, *args): return _eigenfaces.IntVector_insert(self, *args)
    def reserve(self, *args): return _eigenfaces.IntVector_reserve(self, *args)
    def capacity(self): return _eigenfaces.IntVector_capacity(self)
    __swig_destroy__ = _eigenfaces.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _eigenfaces.IntVector_swigregister
IntVector_swigregister(IntVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _eigenfaces.StringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _eigenfaces.StringVector___nonzero__(self)
    def __bool__(self): return _eigenfaces.StringVector___bool__(self)
    def __len__(self): return _eigenfaces.StringVector___len__(self)
    def pop(self): return _eigenfaces.StringVector_pop(self)
    def __getslice__(self, *args): return _eigenfaces.StringVector___getslice__(self, *args)
    def __setslice__(self, *args): return _eigenfaces.StringVector___setslice__(self, *args)
    def __delslice__(self, *args): return _eigenfaces.StringVector___delslice__(self, *args)
    def __delitem__(self, *args): return _eigenfaces.StringVector___delitem__(self, *args)
    def __getitem__(self, *args): return _eigenfaces.StringVector___getitem__(self, *args)
    def __setitem__(self, *args): return _eigenfaces.StringVector___setitem__(self, *args)
    def append(self, *args): return _eigenfaces.StringVector_append(self, *args)
    def empty(self): return _eigenfaces.StringVector_empty(self)
    def size(self): return _eigenfaces.StringVector_size(self)
    def clear(self): return _eigenfaces.StringVector_clear(self)
    def swap(self, *args): return _eigenfaces.StringVector_swap(self, *args)
    def get_allocator(self): return _eigenfaces.StringVector_get_allocator(self)
    def begin(self): return _eigenfaces.StringVector_begin(self)
    def end(self): return _eigenfaces.StringVector_end(self)
    def rbegin(self): return _eigenfaces.StringVector_rbegin(self)
    def rend(self): return _eigenfaces.StringVector_rend(self)
    def pop_back(self): return _eigenfaces.StringVector_pop_back(self)
    def erase(self, *args): return _eigenfaces.StringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _eigenfaces.new_StringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _eigenfaces.StringVector_push_back(self, *args)
    def front(self): return _eigenfaces.StringVector_front(self)
    def back(self): return _eigenfaces.StringVector_back(self)
    def assign(self, *args): return _eigenfaces.StringVector_assign(self, *args)
    def resize(self, *args): return _eigenfaces.StringVector_resize(self, *args)
    def insert(self, *args): return _eigenfaces.StringVector_insert(self, *args)
    def reserve(self, *args): return _eigenfaces.StringVector_reserve(self, *args)
    def capacity(self): return _eigenfaces.StringVector_capacity(self)
    __swig_destroy__ = _eigenfaces.delete_StringVector
    __del__ = lambda self : None;
StringVector_swigregister = _eigenfaces.StringVector_swigregister
StringVector_swigregister(StringVector)

class IntVectorVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVectorVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVectorVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _eigenfaces.IntVectorVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _eigenfaces.IntVectorVector___nonzero__(self)
    def __bool__(self): return _eigenfaces.IntVectorVector___bool__(self)
    def __len__(self): return _eigenfaces.IntVectorVector___len__(self)
    def pop(self): return _eigenfaces.IntVectorVector_pop(self)
    def __getslice__(self, *args): return _eigenfaces.IntVectorVector___getslice__(self, *args)
    def __setslice__(self, *args): return _eigenfaces.IntVectorVector___setslice__(self, *args)
    def __delslice__(self, *args): return _eigenfaces.IntVectorVector___delslice__(self, *args)
    def __delitem__(self, *args): return _eigenfaces.IntVectorVector___delitem__(self, *args)
    def __getitem__(self, *args): return _eigenfaces.IntVectorVector___getitem__(self, *args)
    def __setitem__(self, *args): return _eigenfaces.IntVectorVector___setitem__(self, *args)
    def append(self, *args): return _eigenfaces.IntVectorVector_append(self, *args)
    def empty(self): return _eigenfaces.IntVectorVector_empty(self)
    def size(self): return _eigenfaces.IntVectorVector_size(self)
    def clear(self): return _eigenfaces.IntVectorVector_clear(self)
    def swap(self, *args): return _eigenfaces.IntVectorVector_swap(self, *args)
    def get_allocator(self): return _eigenfaces.IntVectorVector_get_allocator(self)
    def begin(self): return _eigenfaces.IntVectorVector_begin(self)
    def end(self): return _eigenfaces.IntVectorVector_end(self)
    def rbegin(self): return _eigenfaces.IntVectorVector_rbegin(self)
    def rend(self): return _eigenfaces.IntVectorVector_rend(self)
    def pop_back(self): return _eigenfaces.IntVectorVector_pop_back(self)
    def erase(self, *args): return _eigenfaces.IntVectorVector_erase(self, *args)
    def __init__(self, *args): 
        this = _eigenfaces.new_IntVectorVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _eigenfaces.IntVectorVector_push_back(self, *args)
    def front(self): return _eigenfaces.IntVectorVector_front(self)
    def back(self): return _eigenfaces.IntVectorVector_back(self)
    def assign(self, *args): return _eigenfaces.IntVectorVector_assign(self, *args)
    def resize(self, *args): return _eigenfaces.IntVectorVector_resize(self, *args)
    def insert(self, *args): return _eigenfaces.IntVectorVector_insert(self, *args)
    def reserve(self, *args): return _eigenfaces.IntVectorVector_reserve(self, *args)
    def capacity(self): return _eigenfaces.IntVectorVector_capacity(self)
    __swig_destroy__ = _eigenfaces.delete_IntVectorVector
    __del__ = lambda self : None;
IntVectorVector_swigregister = _eigenfaces.IntVectorVector_swigregister
IntVectorVector_swigregister(IntVectorVector)


def test(*args):
  return _eigenfaces.test(*args)
test = _eigenfaces.test
class Eigenfaces2(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Eigenfaces2, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Eigenfaces2, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _eigenfaces.delete_Eigenfaces2
    __del__ = lambda self : None;
    def __init__(self, *args): 
        this = _eigenfaces.new_Eigenfaces2(*args)
        try: self.this.append(this)
        except: self.this = this
    def save(self, *args): return _eigenfaces.Eigenfaces2_save(self, *args)
    def load(self, *args): return _eigenfaces.Eigenfaces2_load(self, *args)
    def train(self, *args): return _eigenfaces.Eigenfaces2_train(self, *args)
    def predictN(self, *args): return _eigenfaces.Eigenfaces2_predictN(self, *args)
    def isTrained(self): return _eigenfaces.Eigenfaces2_isTrained(self)
Eigenfaces2_swigregister = _eigenfaces.Eigenfaces2_swigregister
Eigenfaces2_swigregister(Eigenfaces2)

# This file is compatible with both classic and new-style classes.


